MODULE PARAMS
   DOUBLE PRECISION, PARAMETER :: TOL = 1D-5
   INTEGER, PARAMETER :: MAXCOUNT = 400
   INTEGER, PARAMETER :: NUGGET = 10
   INTEGER, PARAMETER :: Pc = 2
   DOUBLE PRECISION, PARAMETER :: CONDTOL = 1D15
END MODULE

